#!/usr/bin/env node
import { execSync } from 'node:child_process'
/**
 * Shinon commit-msg Gate
 * Prüft: verbotene Footer, 200 Wörter Prosa, Bullet-Verbot, Datei-Nennung.
 */
import fs from 'node:fs'

const msgFile = process.argv[2]
if (!msgFile || !fs.existsSync(msgFile)) {
  console.error('💥 commit-msg Gate: keine Commit-Nachricht gefunden')
  process.exit(1)
}

const raw = fs.readFileSync(msgFile, 'utf8')
const lines = raw.split('\n')

// Titel = erste nicht-leere Zeile, Body = alles danach (Kommentare # raus)
let titleEnd = 0
for (let i = 0; i < lines.length; i++) {
  if (lines[i].trim() === '' || lines[i].startsWith('#')) continue
  titleEnd = i
  break
}
const bodyLines = lines.slice(titleEnd + 1).filter((l) => !l.startsWith('#'))
const body = bodyLines.join('\n').trim()
const fullText = raw

// 1) Verbotene Footer — Hard-Fail (case-insensitive)
const forbidden = [
  /co-authored-by/i,
  /generated by/i,
  /powered by\s+(chatgpt|claude|gemini|openai|anthropic)/i,
  /noreply@codebuff\.com/i,
]
for (const re of forbidden) {
  if (re.test(fullText)) {
    console.error(`💥 Commit-Gate Hard-Fail — verbotener Footer erkannt: ${re}`)
    console.error(
      '   Entferne jede KI-/Werbe-Signatur aus der Commit-Nachricht. Kein Co-authored-by, kein Generated by.',
    )
    process.exit(1)
  }
}

// 2) Bullet-Verbot — nur im Body
for (const line of bodyLines) {
  const trimmed = line.trimStart()
  if (
    trimmed.startsWith('* ') ||
    trimmed.startsWith('- ') ||
    trimmed.startsWith('• ')
  ) {
    console.error(
      '💥 Commit-Gate Hard-Fail — Bullet Points im Body verboten (*, -, •)',
    )
    console.error(`   Offending line: "${line}"`)
    console.error('   Schreib Fließtext-Prosa, keine Aufzählungen.')
    process.exit(1)
  }
}

// 3) 200 Wörter Minimum im Body
const words = body.split(/\s+/).filter((w) => w.length > 0)
if (words.length < 200) {
  console.error(
    `💥 Commit-Gate Hard-Fail — Commit-Body zu kurz: ${words.length} Wörter, benötigt ≥200`,
  )
  console.error(
    '   Schreib ausführliche Prosa: warum und wie wurde geändert, technische Begründung, Auswirkungen.',
  )
  process.exit(1)
}

// 4) Namentliche Nennung jeder modifizierten Datei
let changed
try {
  const out = execSync('git diff --cached --name-only', { encoding: 'utf8' })
  changed = out
    .split('\n')
    .map((s) => s.trim())
    .filter(Boolean)
} catch (error) {
  console.error(
    '💥 Commit-Gate Hard-Fail — staged Dateien konnten nicht ermittelt werden',
  )
  console.error(`   ${error.message}`)
  process.exit(1)
}

const bodyLower = body.toLowerCase()
const missing = []
for (const f of changed) {
  const base = f.split('/').pop().toLowerCase()
  const full = f.toLowerCase()
  if (!bodyLower.includes(full) && !bodyLower.includes(base)) {
    missing.push(f)
  }
}

if (missing.length > 0) {
  console.error(
    '💥 Commit-Gate Hard-Fail — folgende geänderte Dateien werden im Body nicht namentlich genannt:',
  )
  for (const m of missing) console.error(`   - ${m}`)
  console.error(
    '   Nenne jede modifizierte Datei im Fließtext und begründe ihre Änderung.',
  )
  process.exit(1)
}

console.log(
  `✅ commit-msg Gate bestanden — ${words.length} Wörter, ${changed.length} Dateien genannt, kein verbotener Footer.`,
)
