/**
 * Reine Commit-Text-Validierung — eine Wahrheit für Hook und CI-Plugin.
 * Kein Git-Zugriff, keine I/O: bekommt Text, liefert Verstöße.
 * So kann der lokale commit-msg Hook und das Remote commit-integrity
 * Plugin dieselben Regeln erzwingen, ohne sie zu duplizieren (docs/REGELWERK_GIT.md).
 */

const FORBIDDEN = [
  { re: /co-authored-by/i, label: 'Co-authored-by' },
  { re: /generated by/i, label: 'Generated by' },
  {
    re: /powered by\s+(chatgpt|claude|gemini|openai|anthropic)/i,
    label: 'Powered by KI',
  },
  { re: /noreply@codebuff\.com/i, label: 'codebuff-Signatur' },
]

const MIN_WORDS = 200

export function parseMessage(raw) {
  const lines = raw.split('\n')
  let titleEnd = 0
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim() === '' || lines[i].startsWith('#')) continue
    titleEnd = i
    break
  }
  const bodyLines = lines.slice(titleEnd + 1).filter((l) => !l.startsWith('#'))
  return { bodyLines, body: bodyLines.join('\n').trim() }
}

export function checkMessage(raw, changedFiles = []) {
  const violations = []
  const { bodyLines, body } = parseMessage(raw)

  for (const { re, label } of FORBIDDEN) {
    if (re.test(raw)) violations.push(`verbotener Footer: ${label}`)
  }

  for (const line of bodyLines) {
    const t = line.trimStart()
    if (t.startsWith('* ') || t.startsWith('- ') || t.startsWith('• ')) {
      violations.push(`Bullet Point im Body: "${line}"`)
      break
    }
  }

  const words = body.split(/\s+/).filter((w) => w.length > 0)
  if (words.length < MIN_WORDS) {
    violations.push(
      `Body zu kurz: ${words.length} Wörter, benötigt ≥${MIN_WORDS}`,
    )
  }

  const bodyLower = body.toLowerCase()
  const missing = changedFiles.filter(
    (f) =>
      !bodyLower.includes(f.toLowerCase()) &&
      !bodyLower.includes(f.split('/').pop().toLowerCase()),
  )
  for (const m of missing)
    violations.push(`Datei nicht namentlich erwähnt: ${m}`)

  return { ok: violations.length === 0, violations, words: words.length }
}
